###############################################
## This is default daemon configuration file ##
###############################################
## `NOTE:` signs is just a dev notes that can help with thinking of implemetation

[Daemon]
schedule = 30
units = "m" # can also be m or s
shuffle = true
## Here only directories supported!
path = "~/Pictures/wallpapers/"
## Here you choose what interfaces is used from program startup, can be empty, in that case daemon will just sleep
## until user activates at least one of accessible interface declared in [Interfaces section]
active_interfaces = ["hyprpanel"]

## NOTE: EVERY interface MUST be saved, so it is accessible from client program
[Interfaces]
## For interface you provide program arguments as a list
## %f for image file passed by daemon when changing wallpaper
## In help message will appear option for enabling or disabling this interface
hyprpanel = ["hyprpanel", "setWallpaper", "%f"]

[Interfaces.swww]
args = [
    "swww", "img",
    "--transition-type", "%transition_type",
    "--transition-fps", "%transition_fps",
    "%f"
]
## Mutable variable, can be const
[Interfaces.swww.variables.transition_fps]
value = 30
#const = true

## Constant can be also declared this way
##[Interfaces.swww.variables]
##transition_fps = 30

## Enum type, cannot be constant
[Interfaces.swww.variables.transition_type]
current = "grow"
options = ["grow", "wipe", "outer"]
## TODO: Add support for that :)
##random = true